### ISSUE TITLE
Guides 4-6

### ISSUE THREAD

**Issue by tannazie** [shotgunsoftware/developer.shotgunsoftware.com#27]
- 4: Schema/Template modification 
 - 5: Getting Updates
 - 6: Taking over a Hook

**Comment by manneohrstrom** [comment]
can we break this out into separate tickets @tannazie ?

**Comment by tannazie** [comment]
Yes! I'd kept it all together to keep things uncluttered, with the intention to break it out when we were ready to work on it. I have created an issue for Guide 4, but not 5 or 6 yet, 2 items/questions:
 - Ideally, I'll wait until the Big PR is merged (hopefully end of this week / beginning of next week), so that the structure will be in place in master, and I can create a proper branch/PR for each of these guides, with the file and image folders created, as opposed to just an issue now and associated PR later
 - it would actually be nice to have some nesting of issues: (ie, big overarching issue, subtasks linked to it), but I'm not sure if we can do that here, and could be convinced that it's not necessary :)
